"""AgentState TypedDict and sub-entities for AdCockpit LangGraph."""
from typing import TypedDict, List, Optional, Dict, Any, Literal


class TaskNode(TypedDict):
    """A single task node in the Supervisor's task graph."""
    id: str
    type: Literal["fetch_data", "analyze", "strategize", "execute", "report"]
    platform: Optional[str]
    params: Dict[str, Any]
    depends_on: List[str]
    status: Literal["pending", "running", "done", "failed", "awaiting_approval"]


class PlatformData(TypedDict):
    """Data fetched from a single platform API call."""
    platform: str
    endpoint: str
    data: List[Dict[str, Any]]
    fetched_at: str
    error: Optional[str]


class StrategyAction(TypedDict):
    """An executable action generated by Strategy/Content/Ecommerce Agent."""
    target_id: str
    target_type: str          # "campaign", "creative", "product", "budget"
    action: str               # "update_bid", "replace_creative", "add_stock", "create_coupon", ...
    params: Dict[str, Any]
    risk_level: Literal["low", "medium", "high"]
    expected_effect: str
    requires_approval: bool


class ExecutionResult(TypedDict):
    """Result of executing a single StrategyAction."""
    action: StrategyAction
    status: Literal["success", "failed", "cancelled", "retrying"]
    response: Optional[Dict[str, Any]]
    error: Optional[str]
    retry_count: int
    executed_at: str


class AgentState(TypedDict):
    """Global state that flows through all LangGraph agent nodes."""
    user_input: str
    task_graph: List[TaskNode]
    platform_data: List[PlatformData]
    analysis_result: Dict[str, Any]
    strategy_actions: List[StrategyAction]
    execution_results: List[ExecutionResult]
    report: Dict[str, Any]
    pending_approval: Optional[List[StrategyAction]]
    conversation_history: List[Dict[str, str]]
    error_log: List[Dict[str, Any]]
    session_id: str
    current_scene: Literal["ad_placement", "content", "ecommerce", "data_analysis", "diagnosis"]
